import type { Task, Meeting, AISuggestion } from "@/types";

export const mockTasks: Task[] = [
  {
    id: "t1",
    title: "Reply to Sara — Q2 budget numbers",
    status: "open",
    priority: "hot",
    bucket: "now",
    source: "slack",
    sourceRef: { slack: { channelId: "finance", ts: "1714000000" } },
    createdAt: new Date(),
    assignee: "me",
    meta: "#finance · 2h ago · leadership sync at 3pm",
    aiDraft: {
      kind: "reply",
      target: { channelId: "finance" },
      body: "Hi Sara — here's Q2: Revenue $1.2M (+18% QoQ), margin 34%. Full deck attached. Ping if you need the raw figures before 3.",
      provenance: ["Q2-plan.pdf"],
      autoApprovable: false,
      state: "proposed",
    },
  },
  {
    id: "t2",
    title: "Send design deck to Marcus",
    status: "open",
    priority: "hot",
    bucket: "now",
    source: "outlook",
    sourceRef: { outlook: { messageId: "msg1" } },
    createdAt: new Date(),
    assignee: "me",
    meta: "Due today 5:00 PM · attachments ready",
  },
  {
    id: "t3",
    title: "Review PR #842 — Auth refactor",
    status: "open",
    priority: "normal",
    bucket: "today",
    source: "slack",
    sourceRef: { slack: { channelId: "eng", ts: "1713900000" } },
    createdAt: new Date(),
    assignee: "me",
    meta: "from Jen · #eng · yesterday",
  },
  {
    id: "t4",
    title: "Approve Q1 expense report",
    status: "open",
    priority: "normal",
    bucket: "today",
    source: "outlook",
    sourceRef: { outlook: { messageId: "msg2" } },
    createdAt: new Date(),
    assignee: "me",
    meta: "HR team · 1 day",
  },
  {
    id: "t5",
    title: "Follow up on vendor contract",
    status: "open",
    priority: "normal",
    bucket: "today",
    source: "personal",
    sourceRef: {},
    createdAt: new Date(),
    assignee: "me",
    meta: "Added Mon · no reply 3 days",
    aiDraft: {
      kind: "email",
      target: { recipient: "vendor@example.com" },
      body: "Quick follow-up on the MSA redline we sent Monday — any updates? Happy to jump on a call if easier.",
      provenance: [],
      autoApprovable: false,
      state: "proposed",
    },
  },
  {
    id: "t6",
    title: "Confirm launch date with marketing",
    status: "open",
    priority: "normal",
    bucket: "today",
    source: "granola",
    sourceRef: { granola: { meetingId: "m1", quote: "Marcus: can you loop in marketing by Fri?" } },
    createdAt: new Date(),
    assignee: "me",
    meta: "Extracted · Product sync · 11:32",
  },
  {
    id: "t7",
    title: "Review API spec — section 3",
    status: "open",
    priority: "normal",
    bucket: "today",
    source: "granola",
    sourceRef: { granola: { meetingId: "m1", quote: "Jen: need your eyes on section 3" } },
    createdAt: new Date(),
    assignee: "me",
    meta: "Extracted · Product sync · 11:32",
  },
  {
    id: "t8",
    title: "Draft hiring rubric — Sr. PM",
    status: "open",
    priority: "normal",
    bucket: "today",
    source: "granola",
    sourceRef: { granola: { meetingId: "m2" } },
    createdAt: new Date(),
    assignee: "me",
    meta: "Extracted · 1:1 w/ David · Tue",
  },
  {
    id: "t9",
    title: "Update roadmap doc with Q3 OKRs",
    status: "open",
    priority: "normal",
    bucket: "this_week",
    source: "personal",
    sourceRef: {},
    createdAt: new Date(),
    assignee: "me",
    meta: "No due date",
  },
  {
    id: "t10",
    title: "Prep notes for Monday offsite",
    status: "open",
    priority: "normal",
    bucket: "this_week",
    source: "personal",
    sourceRef: {},
    createdAt: new Date(),
    assignee: "me",
    meta: "Due Mon 28 Apr",
  },
  {
    id: "t11",
    title: "Send NDA to legal",
    status: "done",
    priority: "normal",
    bucket: "this_week",
    source: "outlook",
    sourceRef: { outlook: { messageId: "msg3" } },
    createdAt: new Date(),
    assignee: "me",
    meta: "Completed 9:14 AM",
  },
  {
    id: "t12",
    title: "Schedule 1:1 with David",
    status: "done",
    priority: "normal",
    bucket: "this_week",
    source: "outlook",
    sourceRef: { outlook: { eventId: "evt1" } },
    createdAt: new Date(),
    assignee: "me",
    meta: "Completed yesterday",
  },
  // Board-supplemental tasks
  {
    id: "t13",
    title: "Approve contract redline",
    status: "open",
    priority: "hot",
    bucket: "now",
    source: "slack",
    sourceRef: { slack: { channelId: "legal", ts: "1714010000" } },
    createdAt: new Date(),
    assignee: "me",
    meta: "Legal · blocked",
  },
  {
    id: "t14",
    title: "Review legal MSA draft",
    status: "open",
    priority: "normal",
    bucket: "this_week",
    source: "outlook",
    sourceRef: { outlook: { messageId: "msg4" } },
    createdAt: new Date(),
    assignee: "me",
    meta: "Due Fri",
  },
  {
    id: "t15",
    title: "Architecture RFC comments",
    status: "open",
    priority: "normal",
    bucket: "this_week",
    source: "slack",
    sourceRef: { slack: { channelId: "eng", ts: "1713800000" } },
    createdAt: new Date(),
    assignee: "me",
    meta: "#eng · Wed",
  },
  {
    id: "t16",
    title: "Follow-up on vendor pricing",
    status: "open",
    priority: "normal",
    bucket: "this_week",
    source: "granola",
    sourceRef: { granola: { meetingId: "m3" } },
    createdAt: new Date(),
    assignee: "me",
    meta: "Vendor call",
  },
  {
    id: "t17",
    title: "Reply in #design-crit",
    status: "done",
    priority: "normal",
    bucket: "this_week",
    source: "slack",
    sourceRef: { slack: { channelId: "design-crit", ts: "1713600000" } },
    createdAt: new Date(),
    assignee: "me",
    meta: "Tue",
  },
  {
    id: "t18",
    title: "Share Q1 retro notes",
    status: "done",
    priority: "normal",
    bucket: "this_week",
    source: "granola",
    sourceRef: { granola: { meetingId: "m4" } },
    createdAt: new Date(),
    assignee: "me",
    meta: "Mon",
  },
  {
    id: "t19",
    title: "Book flights for offsite",
    status: "done",
    priority: "normal",
    bucket: "this_week",
    source: "personal",
    sourceRef: {},
    createdAt: new Date(),
    assignee: "me",
    meta: "Mon",
  },
];

export const mockMeeting: Meeting = {
  id: "m1",
  provider: "granola",
  title: "Product sync with Eng",
  startedAt: new Date("2026-04-24T10:44:00"),
  endedAt: new Date("2026-04-24T11:32:00"),
  attendees: [
    { id: "u1", name: "Marcus", initial: "M" },
    { id: "u2", name: "Jen", initial: "J" },
    { id: "u3", name: "Kim", initial: "K" },
    { id: "u4", name: "Alex", initial: "A" },
    { id: "u5", name: "Richard", initial: "R" },
  ],
  transcriptUrl: "#",
  extractedActions: [
    {
      id: "ea1",
      taskDraft: { title: "Confirm launch date with marketing", source: "granola" },
      quote: "Marcus: \"…can you loop in marketing by Fri?\"",
      speaker: "Marcus",
      confidence: 0.92,
    },
    {
      id: "ea2",
      taskDraft: { title: "Review API spec before Tuesday", source: "granola" },
      quote: "Jen: \"…need your eyes on section 3…\"",
      speaker: "Jen",
      confidence: 0.88,
    },
  ],
};

export const mockSuggestions: AISuggestion[] = [
  {
    id: "s1",
    kind: "draft_ready",
    label: "Draft ready · Slack",
    body: '"Thanks — I\'ll send the deck by EOD Thursday. Let me know if earlier works."',
    actions: [
      { label: "Send", variant: "primary" },
      { label: "Edit", variant: "secondary" },
      { label: "Skip", variant: "ghost" },
    ],
    relatedTaskIds: ["t2"],
  },
  {
    id: "s2",
    kind: "batch",
    label: "Batch suggestion",
    body: "3 'budget' tasks could be handled together in a 25 min block Wed 2:00 PM.",
    actions: [
      { label: "Schedule", variant: "primary" },
      { label: "Dismiss", variant: "ghost" },
    ],
    relatedTaskIds: ["t1", "t4"],
  },
  {
    id: "s3",
    kind: "turn_into_meeting",
    label: "Turn into meeting",
    body: '"Confirm launch date" may need marketing + eng. Propose 15 min Fri 10:00?',
    actions: [
      { label: "Create invite", variant: "primary" },
      { label: "Not now", variant: "ghost" },
    ],
    relatedTaskIds: ["t6"],
  },
  {
    id: "s4",
    kind: "auto_handle",
    label: "Auto-handle",
    body: '"Can you share the Q2 doc?" → reply with Q2-plan.pdf link.',
    actions: [
      { label: "Approve", variant: "primary" },
      { label: "Review", variant: "secondary" },
    ],
    relatedTaskIds: [],
    dashed: true,
  },
];
